# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
# the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.


def generate_fibonacci_sequence(max_int):
    result = [1, 2]
    a, b = 1, 2
    while a + b < max_int:
        result.append(a + b)
        a, b = b, result[-1]
    return result


four_mil_fibber = filter(lambda x: x & 1 == 0, generate_fibonacci_sequence(4000000))
print(sum(list(four_mil_fibber)))
